global:
  scrape_interval: 15  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
health_configs:
  - monitor_name: 'JaegerAgents'
    monitor_item:
      uri: 
        ['http://localhost:14271/',
        'http://localhost:14271/' ]
      type: 'ping'
  - monitor_name: 'NSQ'
    monitor_item:
      uri: 
        ['http://localhost:4151/ping/']
      type: 'ping'

  - monitor_name: 'kafka'
    monitor_item:
     uri: 
       ['http://10.167.197.254:9000/kafdrop/consumer/jaeger-injest-1']
     type: 'kafdrop'
